# Static
- type: latheRecipePack
  id: SecurityAmmoStaticQB
  recipes:
  - MagazineMagnumEmpty
  - MagazineMagnum
  - MagazineMagnumStun

# Dynamic
- type: latheRecipePack
  id: SecurityAmmoDynamicQB
  recipes:
  - MagazineLightRifleUranium
  - MagazineLightRifleIncendiary
  - SpeedLoaderMagnumHoly
  - MagazineBoxMagnumHoly
